name: Python CI & Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest

  deploy:
    needs: test  # Wait for tests to pass
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Deploy to Ubuntu via SSH
        uses: appleboy/ssh-action@master
        with:
          host: 192.168.68.68
          username: kishan  # Replace with your server username
          key: ${{ secrets.SSH_PRIVATE_KEY }}  # Store your SSH key in GitHub Secrets
          script: |
            cd /home/kishan/githubaction || exit 1
            git fetch origin
            git reset --hard origin/main  # Force sync with remote
            sudo systemctl restart your-app-service  # Only if applicable
            
           
    


