name: Python CI

# Trigger the workflow
on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main
        
jobs:
    test:
        runs-on: ubuntu-latest

        steps:
            # step 01 -  checkout the code from repository
            - name: check out code
              uses: actions/checkout@v2

            #step 02 -set up python
            - name: set up python
              uses: actions/setup-python@v2
              with:
                python-version: '3.8'

            #step 03 - install dependencies
            - name: install dependencies
              run: |
                python -m pip install --upgrade pip
                pip install -r requirements.txt
            
            - name: run test
              run: pytest
        

    


